/**********************************************************
 * this file is generated by configure on 
 * So 19. Aug 14:54:18 CEST 2007
 *********************************************************/

#ifndef CONFIG_H
#define CONFIG_H

/* os type */
#define OS "linux"

/* libnamegen version */
#define MAJOR_VERSION	0
#define MINOR_VERSION	30

/* data directory */
#define DATA_DIR "/home/thorsten/rpg_essentials/names/data"

#endif /* CONFIG_H */

